# Generated by Django 3.2.5 on 2021-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelpractice', '0002_userinfo_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
