# Generated by Django 3.2.5 on 2021-08-11 16:50

from django.db import migrations, models
import modelextra.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0002_alter_userbio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[modelextra.models.validate_age]),
        ),
    ]
